name: 'BDE_AirBnB'
version: '1.0.0'
config-version: 2
profile: 'BDE_AirBnB'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

BDE_AirBnB:
 models:
